version: "3.8"

services:

  frontend:
    build: ./keycloak
    container_name: keycloak-app
    ports:
        - 80:80
    environment:
        - KEYCLOAK_URL=http://keycloak:8080
        - KEYCLOAK_REALM=primo-reame
        - KEYCLOAK_CLIENT_ID=keycloak-esempio
    depends_on:
        - keycloak
        - backend
    
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 9000:9000
    environment: 
      - APP_NAME=movies-app
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=primo-reame
    depends_on:
      - keycloak
    
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    #  - KEYCLOAK_IMPORT=/tmp/realm-test.json
    #volumes:
    #  - ./infra/keycloak/realm-test.json:/tmp/realm-test.json
    #command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    depends_on: 
     - postgres
 
  postgres:
    image: postgres:alpine
    environment:
        - POSTGRES_PASSWORD=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_DB=keycloak
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    
  
    